[env:esp32doit-devkit-v1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32doit-devkit-v1
framework = arduino
upload_speed = 921600
monitor_speed = 115200

board_build.partitions = default.csv
board_build.filesystem = littlefs

build_flags = 
    -DCORE_DEBUG_LEVEL=0
lib_deps = 
    RobTillaart/RunningMedian
    plerup/espsoftwareserial
    mikalhart/TinyGPSPlus
    mathieucarbou/ESPAsyncWebServer
    bblanchon/ArduinoJson
    mathieucarbou/AsyncTCP